export const ADD_PDF_DOCUMENT = "ADD_PDF_DOCUMENT";
export const GET_PDF_DOCUMENTS = "GET_PDF_DOCUMENTS";
export const GET_DOCUMENT_ANNOTATIONS = 'GET_DOCUMENT_ANNOTATIONS';
export const UPDATE_DOCUMENT_ANNOTATIONS = 'UPDATE_DOCUMENT_ANNOTATIONS';
export const DELETE_DOCUMENT_ANNOTATIONS = 'DELETE_DOCUMENT_ANNOTATIONS';
export const CREATE_DOCUMENT_ANNOTATIONS = 'CREATE_DOCUMENT_ANNOTATIONS';